### ISSUE TITLE
Settings don't save

### ISSUE THREAD

**Issue by Musyanon** [crobibero/jellyfin-plugin-tmdb-trailers#2]
Hello,

If I change settings and click to save, the page resfresh and nothing change.

**Comment by crobibero** [comment]
That is a bug with jellyfin-web. After the refresh you have to configure again, then everything should save.

**Comment by Musyanon** [comment]
I have try but doesn't work, I check a box setting and click save, I have the refresh again and the settings rollback to default.

**Comment by crobibero** [comment]
Check box -> Save -> allow refresh -> Check box save

**Comment by Musyanon** [comment]
Yes but doesn't work, I have just try now ^^

**Comment by crobibero** [comment]
Sorry, I can't replicate the issue. I'm fairly certain it's a bug in jellyfin-web.

**Comment by Musyanon** [comment]
Ok, stange, I have try with Microsoft Edge and Google Chrome same issue...
You have the latest version of Jellyfin ?
Btw I while compile the source with my settings directly :)

**Comment by crobibero** [comment]
This should be fixed for Jellyfin 10.7 and plugin version 5.2021.102.250
