### ISSUE TITLE
how install? 

### ISSUE THREAD

**Issue by JoseMariani** [crobibero/jellyfin-plugin-tmdb-trailers#25]
i add repo in repositories and dont show the extension

**Comment by crobibero** [comment]
The plugin is only available for Jellyfin server 10.8+

**Comment by JoseMariani** [comment]
Excuse my ignorance, what do you mean by 10.8? I downloaded the windows installer, will it be that the windows installer is less than that version 10.8 that you mention?

**Comment by crobibero** [comment]
10.8 is in beta, so you would need to download the beta installer

It can currently be found on this page: https://repo.jellyfin.org/releases/server/windows/stable-pre/
