### ISSUE TITLE
Setting Intro Count: to 1, The number of trailers to play as intros to 1 causes playback in only android app to fail.

### ISSUE THREAD

**Issue by Anexgohan** [crobibero/jellyfin-plugin-tmdb-trailers#38]
[log_20220906.log](https://github.com/crobibero/jellyfin-plugin-tmdb-trailers/files/9494391/log_20220906.log)
Hello,
I found out that the intros will not play for only the android devices if Intro Count: is set to 1,
Other devices work just fine tested on Firestick, Windows Chrome, firefox, edge browser and on android chrome browser, these all display the intro trailer.

Only the Jellyfin android app fails to show/play the trailers.

**Comment by crobibero** [comment]
I recommend opening an issue in the Android client repo as it isnt a plugin bug.
