### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by LoganJFisher** [crobibero/jellyfin-plugin-tmdb-trailers#43]
I'm on Jellyfin 10.8.5-1-ls181

I've added the repository, but nothing is added to the catalog list. I've tried restarting Jellyfin for good measure, but that didn't help.

**Comment by crobibero** [comment]
I cant reproduce this. What is the repo that you added to Jellyfin?

**Comment by LoganJFisher** [comment]
https://github.com/crobibero/jellyfin-plugin-tmdb-trailers.git

**Comment by crobibero** [comment]
The repo is at the bottom of the readme.
https://raw.githubusercontent.com/crobibero/jellyfin-plugin-tmdb-trailers/master/manifest.json

**Comment by LoganJFisher** [comment]
Oh, I see. Sorry. Thank you.
