### ISSUE TITLE
Add an Setting to hide the MenuButton TMDB Trailers

### ISSUE THREAD

**Issue by EGUltraTM** [crobibero/jellyfin-plugin-tmdb-trailers#52]
Im using my Media Server also with kids. So i locked some Librarys out. But the TMDB Trailers Menu Button is always there so you can also watch as kid movie trailers. 

Would be nice if we could hide it form the menu as first step.
And may integrate it to the restriction maybe as part of an library like the Collections is.

**Comment by crobibero** [comment]
You can already hide it per user under User -> Access -> Channel Access
If that doesn't do what you want please provide screenshots.

**Comment by EGUltraTM** [comment]
Oh shit yes i see it. 
damn it. Havent seen that xD sorry.

Other question i set everything to german. 
1.Setting de-DE
2. Setting DE
but still got all stuff in en-US the trailers

**Comment by crobibero** [comment]
I havent actually tested the language code, it is very possible it does nothing.

**Comment by JamsRepos** [comment]
> You can already hide it per user under User -> Access -> Channel Access If that doesn't do what you want please provide screenshots.

Whilst this does work, this means that users cannot see the Trailers within the Trailers section under a Movie library. I'd like the channel to not show up in the main menu but rather just within the Trailers tab.
