### ISSUE TITLE
Language option only for titles?

### ISSUE THREAD

**Issue by Riddler84** [crobibero/jellyfin-plugin-tmdb-trailers#53]
Is it correct, that the language option is only there to show me the localized movie titles, but not the actual trailers in my language?
If that's the case, is it planned for the future? Otherwise, I have to disable the plugin, because not everyone who uses my server understands English. At least not well enough.

**Comment by crobibero** [comment]
The language code is used to get trailers from tmdb that have the code attached. If tmdb doesnt return the correct trailer there is nothing I can do.
