### ISSUE TITLE
Getting a Plugin Malfunction when installing 10.0.0.0

### ISSUE THREAD

**Issue by Gaffers2277** [crobibero/jellyfin-plugin-tmdb-trailers#71]
As the title states it says Malfunction and doesn't have any settings when clicking on the plugin. Tired using 8.0.0.0 but it just superceded back to 10.0.0.0. Is this plugin still working and is it being worked on?

**Comment by crobibero** [comment]
This plug-in works fine for me with Jellyfin 10.8.9. What version of Jellyfin are you running? Please provide logs of why it is being marked as malfunctioned.

**Comment by Gaffers2277** [comment]
I tried to install it again this morning and it seems to be working now. Not sure what happened last night but it seems to be okay now.
