### ISSUE TITLE
Does this only take trailers from TMDB?

### ISSUE THREAD

**Issue by Maltavius** [crobibero/jellyfin-plugin-tmdb-trailers#74]
Almost all of my local files already have a -trailer.mp4 or similar. 
Why go through the trouble of downloading a YouTube-trailer when I already have them.

The documentation or "Help"-link in the Plugin only goes to this GitHub-page where it states how to compile and install it (when there already is a compiled release present).

It does nothing to explain WHAT the plugin actually does.

**Comment by crobibero** [comment]
This plugin does not scan local directories. It pulls youtube links from TMDb and attempts to make them available inside of Jellyfin.

Support for `-trailer` is build into the core server.

**Comment by Maltavius** [comment]
-trailer support in Core doesn't st all populate the Trailer Channel.
